// Sign Up
export const SIGN_UP_IDENTIFIER_IS_DUPLICATAED =
  'SIGN_UP_IDENTIFIER_IS_DUPLICATAED';
export const SIGN_UP_IDENTIFIER_IS_NOT_EXIST =
  'SIGN_UP_IDENTIFIER_IS_NOT_EXIST';
export const SIGN_UP_CODE_INCORRECT = 'SIGN_UP_CODE_INCORRECT';
export const SIGN_UP_CODE_IS_EXPIRED = 'SIGN_UP_CODE_IS_EXPIRED';
export const USER_IS_ALREADY_REGISTERED = 'USER_IS_ALREADY_REGISTERED';

// Sign In
export const MFA_CODE_NOT_EXIST = 'MFA_CODE_NOT_EXIST';
export const MFA_CODE_IS_EXPIRED = 'MFA_CODE_IS_EXPIRED';
export const MFA_CODE_INCORRECT = 'MFA_CODE_INCORRECT';
export const PASSWORD_INCORRECT = 'PASSWORD_INCORRECT';
export const USER_IS_NOT_KYC_VERIFF_VERIFIED =
  'USER_IS_NOT_KYC_VERIFF_VERIFIED';
export const USER_IS_SUSPENDED = 'USER_IS_SUSPENDED';
export const USER_IS_CLOSED = 'USER_IS_CLOSED';

// Get Me
export const USER_IS_NOT_EXIST = 'USER_IS_NOT_EXIST';
export const UNAUTHORIZED = 'UNAUTHORIZED';
//jwt token
export const JWT_TOKEN_GENERATION_FAILED = 'JWT_TOKEN_GENERATION_FAILED'
